<html>
<head>
<title>Clasificaci&oacute;n del riesgo laboral</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<script type="text/javascript"
	src="<?php echo $this->dir_ucid;?>js/imporcss.js"></script>
<script language="javascript" type="text/javascript">importarCSS(window.parent.parent.UCID.portal.perfil.dirCss);</script>
<style>
</style>
</head>
<body>
<script type="text/javascript"
	src="<?php echo $this->dir_extjs;?>js/ext-base.js"></script>
<script type="text/javascript"
	src="<?php echo $this->dir_extjs;?>js/ext-all.js"></script>
<script type="text/javascript"
	src="<?php echo $this->dir_ucid;?>js/ucid-all.js"></script>
<script type="text/javascript" src="/pvd/comun/views/js/utiles/extensiones.js"></script>
<script type="text/javascript" src="/pvd/comun/views/js/utiles/Utiles.js"></script>
<script type="text/javascript" src="/pvd/comun/views/js/utiles/validadores.js"></script>
<script type="text/javascript" src="/pvd/comun/views/js/utiles/DateRange.js"></script>
<script type="text/javascript" src="/pvd/comun/views/js/utiles/RowExpander.js"></script>
<?php echo $this->jsayuda;?>
<script type="text/javascript" src="../../views/js/nomclasificacionriesgo/nomclasificacionriesgoComponent.js"></script> 
<script type="text/javascript" src="../../views/js/nomclasificacionriesgo/nomclasificacionriesgo.js"></script> 
	
</body>
</html>
